version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - backend
    networks:
      - seo-network
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - GIN_MODE=release
      - PORT=8082
    ports:
      - "127.0.0.1:8082:8082"
    networks:
      - seo-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`seo-optimizer.elvynprise.xyz`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8082"

networks:
  seo-network:
    driver: bridge 