version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - seo-network
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - GIN_MODE=release
    expose:
      - "8081"
    networks:
      - seo-network
    restart: unless-stopped

networks:
  seo-network:
    driver: bridge 