version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - seo-network
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=/api
    security_opt:
      - no-new-privileges:true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - GIN_MODE=release
      - PORT=8082
      - DOCKER_NETWORK=172.0.0.0/8
      - RATE_LIMIT_REQUESTS=10
      - RATE_LIMIT_DURATION=1
    ports:
      - "8082:8082"
    networks:
      - seo-network
    restart: unless-stopped
    volumes:
      - seo-stats:/app/data
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`seo-optimizer.elvynprise.xyz`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8082"

networks:
  seo-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/16

volumes:
  seo-stats: 